ignore:
  files:
    - e2e/*
    - pkg/*
    - "**/testdata/**"

rules:
  custom:
    disallow-rego-v1:
      level: error
    missing-metadata:
      level: error
      except-rule-path-pattern: \.report$
      # TODO: this should be in the default config, but it seems
      #       like the ignore attribute isn't read from there
      ignore:
        files:
          - "*_test.rego"
    naming-convention:
      # Regal naming conventions configuration. Note that this is disabled by default, and
      # is meant only to be run every once in a while to ensure we stick to our conventions.
      # These conventions are not static, and the correct "fix" to a naming violation may
      # very well be to update this configuration rather than the code.
      #
      # To check compliance:
      # regal lint --enable naming-convention bundle
      #
      # See naming.md for rationale and examples of these conventions.
      # NOTE: that this check is not automated, but intended to be used occasionally.
      level: ignore
      conventions:
        - pattern: '\b[a-z_]{5,}\b'
          names:
            # indices
            - i
            - j
            - k
            # count / length
            - n
            # rego types
            - arr
            - obj
            - set
            - str
            - num
            # imaginary 'types'
            - coll
            - seq
            - item
            # ast types
            - pkg
            - imp
            - ref
            - refs
            - var
            - vars
            - fun
            - arg
            - args
            - term
            - terms
            - expr
            - exprs
            - rule
            - head
            - body
            - call
            - comp
            - node
            # ast attributes and related
            - key
            - keys
            - val
            - vals
            - type
            # common
            - file
            - text
            - line
            - rows
            - cols
            - loc
            - end
            - col
            - row
            - agg
            - aggs
            - cfg
            - word
            - start
            - link
            - len
            - kind
            - rest
            - name
            - pos
            - sub
            - sup
            - last
            - next
            - lhs
            - rhs
            - path
            - url
            - uri
            - other
            - diff
            - dir
          targets:
            - var
      ignore:
        files:
          - "*_test.rego"
    narrow-argument:
      level: error
      exclude-args:
        - cfg
        - metadata
        - rule
    one-liner-rule:
      level: error
    prefer-value-in-head:
      level: error
      only-scalars: true
      include-interpolated: true
  idiomatic:
    use-array-flatten:
      flag-wrapped-concat: true
  performance:
    equals-over-count:
      level: error
      ignore:
        files:
          - "*_test.rego"
  style:
    line-length:
      level: error
      non-breakable-word-threshold: 100
    prefer-snake-case:
      level: error
      ignore:
        files:
          # This package is used to build the LSP initialize
          # response, and names must conform to the specification
          - "**/bundle/regal/lsp/initialize/initialize.rego"
  imports:
    unresolved-reference:
      level: error
      except-paths:
        - data.eval.**
        - data.internal**
        - data.schema.**
        - data.client.**
        - data.server.**
        - data.workspace.**
        - data.regal.config.provided**
        - data.custom.regal**
