version: "2"
linters:
  default: all
  disable:
    # these linters are disabled either because they
    # are annoying or because they are deprecated
    - dupword
    - err113
    - exhaustruct
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocyclo
    - godox
    - inamedparam
    - ireturn
    - mnd
    - nestif
    - noinlineerr
    - nonamedreturns
    - promlinter # we don't use Prometheus
    - protogetter # we don't have protobuf types
    - rowserrcheck # we don't use SQL
    - sqlclosecheck # we don't use SQL
    - testifylint # not used here
    - testpackage
    - unqueryvet # no SQL here
    - varnamelen
    - wrapcheck
    - wsl # replaced by wsl_v5
  settings:
    cyclop:
      max-complexity: 40 # default is 10
    depguard:
      rules:
        main:
          deny:
            - pkg: gopkg.in/yaml.v2
              desc: use yaml.v3 only
    errcheck:
      exclude-functions:
        - (*github.com/olekukonko/tablewriter.Table).Append
        - (*github.com/olekukonko/tablewriter.Table).Render
    gocritic:
      enable-all: true
      disabled-checks:
        - importShadow
        - initClause
        - whyNoLint # not all nolint comments need explanations
        - hugeParam # investigate later, but some of these breaks API signatures
        - unnamedResult
    govet:
      disable:
        - shadow
        - fieldalignment
      enable-all: true
    perfsprint:
      err-error: true
    revive:
      rules:
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#unused-parameter
        - name: unused-parameter
          arguments:
            - allowRegex: ^_
          severity: warning
          disabled: false
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#unused-receiver
        - name: unused-receiver
          arguments:
            - allowRegex: ^_
          severity: warning
          disabled: false
    staticcheck:
      checks:
        - all
    tagliatelle:
      case:
        rules:
          json: snake
    unused:
      exported-fields-are-used: false
    usetesting:
      context-background: true
      context-todo: true
      os-create-temp: true
      os-temp-dir: true
  exclusions:
    rules:
      - path: '(.+)_test\.go'
        linters:
          - forcetypeassert
          - godot
      - path: internal/lsp
        linters:
          - tagliatelle
      - path: pkg/config
        linters:
          - tagliatelle
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - scanner.go
      - tokens.go
    warn-unused: true
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/open-policy-agent/opa)
        - prefix(github.com/open-policy-agent/regal)
        - blank
        - dot
