version: "2"
linters:
  default: all
  disable:
    # these linters are disabled either because they
    # are annoying or because they are deprecated
    - dupword
    - err113
    - exhaustruct
    - exhaustruct_v5
    - exhaustive
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocyclo
    - godox
    - gomodguard # replace by gomodguard_v2
    - inamedparam
    - ireturn
    - mnd
    - nestif
    - noinlineerr
    - nonamedreturns
    - promlinter # we don't use Prometheus
    - protogetter # we don't have protobuf types
    - rowserrcheck # we don't use SQL
    - sqlclosecheck # we don't use SQL
    - testifylint # not used here
    - testpackage
    - unqueryvet # no SQL here
    - varnamelen
    - wrapcheck
    - wsl # replaced by wsl_v5
  settings:
    cyclop:
      max-complexity: 40 # default is 10
    depguard:
      rules:
        main:
          deny:
            - pkg: gopkg.in/yaml.v2
              desc: use yaml.v3 only
    errcheck:
      exclude-functions:
        - (*github.com/olekukonko/tablewriter.Table).Append
        - (*github.com/olekukonko/tablewriter.Table).Render
        - (*gopkg.in/yaml.v3.Encoder).Encode
        - (io.Writer).Write
        - (*os.File).WriteString
    gocritic:
      enable-all: true
      disabled-checks:
        - importShadow
        - initClause
        - whyNoLint # not all nolint comments need explanations
        - hugeParam # investigate later, but some of these breaks API signatures
        - unnamedResult
    gosec:
      excludes:
        # taint analysis. not relevant as Regal assumes trusted user
        - G703
        - G704
        - G706
    govet:
      disable:
        - shadow
        - fieldalignment
      enable-all: true
    perfsprint:
      err-error: true
    revive:
      enable-all-rules: true
      rules:
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#unused-parameter
        - name: unused-parameter
          arguments:
            - allowRegex: ^_
          severity: warning
          disabled: false
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#unused-receiver
        - name: unused-receiver
          arguments:
            - allowRegex: ^_
          severity: warning
          disabled: false
        # covered by lll linter
        - name: line-length-limit
          disabled: true
        # covered by errcheck linter
        - name: unhandled-error
          disabled: true
        # covered by forcetypeassert linter
        - name: unchecked-type-assertion
          disabled: true
        - name: cyclomatic
          disabled: true
        - name: cognitive-complexity
          disabled: true
        - name: add-constant
          disabled: true
        - name: max-public-structs
          disabled: true
        - name: flag-parameter
          disabled: true
        - name: blank-imports
          disabled: true
        - name: deep-exit
          disabled: true
        - name: function-length
          disabled: true
        - name: nested-structs
          disabled: true
        - name: import-shadowing
          disabled: true
        - name: package-naming
          disabled: true
        - name: var-naming
          disabled: true
        - name: unexported-return
          disabled: true
        - name: comment-spacings
          arguments:
            - "nolint"
        - name: import-alias-naming
          disabled: true
        - name: function-result-limit
          disabled: true
        - name: confusing-naming
          disabled: true
        - name: modifies-value-receiver
          disabled: true
        - name: enforce-switch-style
          disabled: true
        - name: unexported-naming
          disabled: true
        - name: max-control-nesting
          disabled: true
        - name: exported
          disabled: true
        - name: indent-error-flow
          disabled: true
    staticcheck:
      checks:
        - all
    tagliatelle:
      case:
        rules:
          json: snake
    unused:
      field-writes-are-uses: false
      exported-fields-are-used: false
      post-statements-are-reads: false
      local-variables-are-used: false
    usetesting:
      context-background: true
      context-todo: true
      os-create-temp: true
      os-temp-dir: true
  exclusions:
    rules:
      - path: '(.+)_test\.go'
        linters:
          - forcetypeassert
          - godot
          - gosec
      - path: internal/lsp
        linters:
          - tagliatelle
      - path: pkg/config
        linters:
          - tagliatelle
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    warn-unused: true
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/open-policy-agent/opa)
        - prefix(github.com/open-policy-agent/regal)
        - blank
        - dot
