- id: regal-lint
  language: golang
  name: policy file linting
  description: policy file linting with Regal from Styra built from source
  entry: regal lint
  files: (\.rego)$

- id: regal-lint-use-path
  language: system
  name: policy file linting
  description: policy file linting with Regal from Styra using system $PATH
  entry: regal lint
  files: (\.rego)$

- id: regal-download
  language: script
  name: policy file linting
  description: policy file linting with Regal downloaded from Github
  entry: build/download-and-run.sh lint
  files: (\.rego)$

- id: regal-fix
  language: golang
  name: policy file fixing
  description: auto-fix policy files with Regal from Styra built from source
  entry: regal fix --force
  files: (\.rego)$

- id: regal-fix-use-path
  language: system
  name: policy file fixing
  description: auto-fix policy files with Regal from Styra using system $PATH
  entry: regal fix --force
  files: (\.rego)$

- id: regal-fix-download
  language: script
  name: policy file fixing
  description: auto-fix policy files with Regal downloaded from Github
  entry: build/download-and-run.sh fix --force
  files: (\.rego)$
