// Package rast provides tools for working with Rego's AST library (not RoAST)
package rast

import (
	"bytes"
	"encoding/json/jsontext"
	"encoding/json/v2"
	"fmt"
	"iter"
	"os"
	"reflect"
	"slices"
	"strings"

	"github.com/open-policy-agent/opa/v1/ast"
	outil "github.com/open-policy-agent/opa/v1/util"
)

// IsBodyGenerated checks if the body of a rule is generated by the parser.
func IsBodyGenerated(rule *ast.Rule) bool {
	if rule.Default || len(rule.Body) == 0 {
		return true
	}

	if rule.Head != nil && rule.Body[0] != nil {
		bodyStart := rule.Body[0].Location
		if bodyStart == rule.Location || rule.Head.Value != nil && bodyStart == rule.Head.Value.Location {
			return true
		}

		if rule.Head.Key != nil &&
			rule.Body[0].Location.Row == rule.Head.Key.Location.Row &&
			rule.Body[0].Location.Col < rule.Head.Key.Location.Col {
			// This is a quirk in the original AST — the generated body will have a location
			// set before the key, i.e. "message"
			return true
		}
	}

	return false
}

// LinesArrayTerm converts a string with newlines into an ast.Term array holding each line.
func LinesArrayTerm(content string) *ast.Term {
	return ArrayTerm(strings.Split(strings.ReplaceAll(content, "\r\n", "\n"), "\n")...)
}

func ArrayTerm(a ...string) *ast.Term {
	if len(a) == 0 {
		return ast.InternedEmptyArray
	}

	return ast.ArrayTerm(outil.Map(a, ast.InternedTerm)...)
}

func AppendLocation(buf []byte, location *ast.Location) []byte {
	n, endRow, endCol := LocationData(location)

	buf = slices.Grow(buf, n)
	buf = append(outil.AppendInt(buf, location.Row), ':')
	buf = append(outil.AppendInt(buf, location.Col), ':')
	buf = append(outil.AppendInt(buf, endRow), ':')

	return outil.AppendInt(buf, endCol)
}

func LocationData(location *ast.Location) (length, endRow, endCol int) {
	endRow, endCol = location.Row, location.Col
	if textLen := len(location.Text); textLen > 0 {
		endRow += bytes.Count(location.Text, []byte("\n"))
		if location.Row == endRow {
			endCol += textLen
		} else {
			endCol = textLen - bytes.LastIndexByte(location.Text, '\n')
		}
	}

	length = 3 + // 3 colons
		outil.NumDigitsInt(location.Row) + outil.NumDigitsInt(location.Col) +
		outil.NumDigitsInt(endRow) + outil.NumDigitsInt(endCol)

	return length, endRow, endCol
}

// Item is a helper function to create an ast.Item with an interned key.
func Item(key string, value *ast.Term) [2]*ast.Term {
	if value == nil {
		value = ast.InternedNullTerm
	}

	return ast.Item(ast.InternedTerm(key), value)
}

// Insert works like ast.Object.Insert but with an interned string key.
func Insert(obj ast.Object, key string, value *ast.Term) ast.Object {
	obj.Insert(ast.InternedTerm(key), value)

	return obj
}

// GetOr retrieves a term from an ast.Value by key, or returns the default value if not found.
func GetOr(val ast.Value, key string, defaultSupplier func() *ast.Term) *ast.Term {
	if obj, ok := val.(ast.Object); ok {
		if term := obj.Get(ast.InternedTerm(key)); term != nil {
			return term
		}
	}

	return defaultSupplier()
}

// GetValue works like ast.Object.Get but with type assertion for the return value,
// and a boolean return indicator.
func GetValue[T ast.Value](obj ast.Object, key string) (T, bool) {
	var zero T

	if term := obj.Get(ast.InternedTerm(key)); term != nil {
		if v, ok := term.Value.(T); ok {
			return v, true
		}
	}

	return zero, false
}

// GetString retrieves a string from an obj by key, or empty string if not found.
func GetString(obj ast.Object, key string) string {
	if strObj, ok := GetValue[ast.String](obj, key); ok {
		return string(strObj)
	}

	return ""
}

// GetInt retrieves an int from an obj by key, or zero if not found.
func GetInt(obj ast.Object, key string) int {
	if val, ok := GetValue[ast.Number](obj, key); ok {
		if i, ok := val.Int64(); ok {
			return int(i)
		}
	}

	return 0
}

// GetBool retrieves a bool from an obj by key, or false if not found.
func GetBool(obj ast.Object, key string) bool {
	if val, ok := GetValue[ast.Boolean](obj, key); ok {
		return bool(val)
	}

	return false
}

// ValuesOfType creates an iterator over the [ast.Value]s of the specified type from a slice of terms.
func ValuesOfType[T ast.Value](terms []*ast.Term) iter.Seq[T] {
	return func(yield func(T) bool) {
		for _, term := range terms {
			if v, ok := term.Value.(T); ok && !yield(v) {
				return
			}
		}
	}
}

// StructToValue converts a struct to ast.Value using 'json' struct tags (e.g., `json:"field,omitempty"`)
// but without an expensive JSON roundtrip.
// Experimental: this is new and not yet battle-tested, so use with caution.
func StructToValue(input any) ast.Value {
	v, t := reflect.ValueOf(input), reflect.TypeOf(input)

	if v.Kind() == reflect.Pointer {
		v, t = v.Elem(), t.Elem()
	}

	kvs := make([][2]*ast.Term, 0, t.NumField())

	for i := range t.NumField() {
		tag := t.Field(i).Tag.Get("json")
		if tag == "" || tag == "-" {
			continue
		}

		value := v.Field(i)

		if comma := strings.Index(tag, ","); comma != -1 {
			rest := tag[comma+1:]
			tag = tag[:comma]

			if strings.Contains(rest, "omitempty") && value.IsZero() {
				continue
			}
		}

		iface := value.Interface()

		val := toAstValue(iface)
		switch v := val.(type) {
		case ast.Null:
			kvs = append(kvs, Item(tag, ast.InternedNullTerm))
		case ast.Boolean:
			kvs = append(kvs, Item(tag, ast.InternedTerm(bool(v))))
		case ast.String:
			kvs = append(kvs, Item(tag, ast.InternedTerm(string(v))))
		case ast.Number:
			if i, ok := v.Int64(); ok {
				kvs = append(kvs, Item(tag, ast.InternedTerm(int(i))))
			} else {
				kvs = append(kvs, Item(tag, ast.NewTerm(val)))
			}
		default:
			kvs = append(kvs, Item(tag, ast.NewTerm(val)))
		}
	}

	return ast.NewObject(kvs...)
}

func toAstValue(v any) ast.Value {
	if v == nil {
		return ast.NullValue
	}

	if av, ok := v.(ast.Value); ok {
		return av
	}

	rv := reflect.ValueOf(v)
	for rv.Kind() == reflect.Pointer {
		if rv.IsNil() {
			return ast.NullValue
		}

		rv = rv.Elem()
	}

	if rm, ok := v.(*jsontext.Value); ok {
		var decoded any
		if err := json.Unmarshal(*rm, &decoded); err != nil {
			return ast.NullValue
		}

		return toAstValue(decoded)
	}

	//nolint:exhaustive
	switch rv.Kind() {
	case reflect.Struct:
		return StructToValue(rv.Interface())
	case reflect.Slice, reflect.Array:
		l := rv.Len()
		if l == 0 {
			return ast.InternedEmptyArrayValue
		}

		arr := make([]*ast.Term, 0, l)
		for i := range l {
			arr = append(arr, internedAny(rv.Index(i).Interface()))
		}

		return ast.NewArray(arr...)
	case reflect.Map:
		kvs := make([][2]*ast.Term, 0, rv.Len())

		for _, key := range rv.MapKeys() {
			var k *ast.Term

			ki := key.Interface()
			if s, ok := ki.(string); ok {
				k = ast.InternedTerm(s)
			} else {
				k = ast.InternedTerm(fmt.Sprint(ki))
			}

			kvs = append(kvs, [2]*ast.Term{k, internedAny(rv.MapIndex(key).Interface())})
		}

		return ast.NewObject(kvs...)
	case reflect.String:
		return ast.InternedValue(rv.String())
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		return ast.InternedValue(rv.Int())
	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
		return ast.InternedValue(rv.Uint())
	case reflect.Float32, reflect.Float64:
		return ast.Number(fmt.Sprint(rv.Float()))
	case reflect.Bool:
		return ast.InternedValue(rv.Bool())
	}
	// Fallback: string representation
	fmt.Fprintln(os.Stderr, "WARNING: Unsupported type for conversion to ast.Value:", rv.Kind())

	return ast.String(fmt.Sprint(v))
}

func internedAny(v any) *ast.Term {
	switch value := v.(type) {
	case bool:
		return ast.InternedTerm(value)
	case string:
		return ast.InternedTerm(value)
	case int:
		return ast.InternedTerm(value)
	case uint:
		return ast.InternedTerm(int(value)) // //nolint:gosec
	case int64:
		return ast.InternedTerm(int(value))
	case float64:
		return ast.FloatNumberTerm(value)
	default:
		return ast.NewTerm(toAstValue(v))
	}
}
