name: Push Tags

on:
  push:
    tags:
      - v[0-9].**

permissions:
  contents: read

jobs:
  goreleaser:
    name: GoReleaser
    runs-on: ubuntu-22.04
    permissions:
      # this is needed to create a release
      contents: write
      # this is needed to create artifacts in ghcr
      packages: write

    steps:
      - name: Check out code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: go.mod
          check-latest: true

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@f06c13b6b1a9625abc9e6e439d9c05a8f2190e94 # v7.2.3
        with:
          install-only: true

      - name: Run GoReleaser
        run: goreleaser release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
