name: "Update EOPA caps"

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  fetch:
    name: Fetch EOPA caps
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    env:
      RQ_VERSION: v0.0.16
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod
      - name: Restore rq cache
        id: cache-rq
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ~/go/bin/rq
          key: ${{ runner.os }}-${{ runner.arch }}-go-rq-${{ env.RQ_VERSION }}
      - run: go install git.sr.ht/~charles/rq/cmd/rq@${{ env.RQ_VERSION }}
        if: steps.cache-rq.outputs.cache-hit != 'true'
      - name: Cache rq binary
        if: steps.cache-rq.outputs.cache-hit != 'true'
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ~/go/bin/rq
          key: ${{ runner.os }}-${{ runner.arch }}-go-rq-${{ env.RQ_VERSION }}
      - run: build/do.rq fetch
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          title: "automated: update capabilities"
          branch: create-pull-request/caps
          add-paths: |
            internal/capabilities/embedded/eopa/*.json
